In [1]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
iris = load_iris()
data, target = iris.data, iris.target

In [9]:
it=iter(data)

In [6]:
for i in it:
    print(i)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.2]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.6 1.4 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4

In [12]:
try:
    print(next(it))
except StopIteration:
    print("The iterator is empty")

[4.7 3.2 1.3 0.2]


In [14]:
##generators
def gen(data,target):
    for i in range(len(data)):
        yield data[i],target[i]

In [17]:
g=gen(data,target)

In [18]:
for i in g:
    print(i)

(array([5.1, 3.5, 1.4, 0.2]), 0)
(array([4.9, 3. , 1.4, 0.2]), 0)
(array([4.7, 3.2, 1.3, 0.2]), 0)
(array([4.6, 3.1, 1.5, 0.2]), 0)
(array([5. , 3.6, 1.4, 0.2]), 0)
(array([5.4, 3.9, 1.7, 0.4]), 0)
(array([4.6, 3.4, 1.4, 0.3]), 0)
(array([5. , 3.4, 1.5, 0.2]), 0)
(array([4.4, 2.9, 1.4, 0.2]), 0)
(array([4.9, 3.1, 1.5, 0.1]), 0)
(array([5.4, 3.7, 1.5, 0.2]), 0)
(array([4.8, 3.4, 1.6, 0.2]), 0)
(array([4.8, 3. , 1.4, 0.1]), 0)
(array([4.3, 3. , 1.1, 0.1]), 0)
(array([5.8, 4. , 1.2, 0.2]), 0)
(array([5.7, 4.4, 1.5, 0.4]), 0)
(array([5.4, 3.9, 1.3, 0.4]), 0)
(array([5.1, 3.5, 1.4, 0.3]), 0)
(array([5.7, 3.8, 1.7, 0.3]), 0)
(array([5.1, 3.8, 1.5, 0.3]), 0)
(array([5.4, 3.4, 1.7, 0.2]), 0)
(array([5.1, 3.7, 1.5, 0.4]), 0)
(array([4.6, 3.6, 1. , 0.2]), 0)
(array([5.1, 3.3, 1.7, 0.5]), 0)
(array([4.8, 3.4, 1.9, 0.2]), 0)
(array([5. , 3. , 1.6, 0.2]), 0)
(array([5. , 3.4, 1.6, 0.4]), 0)
(array([5.2, 3.5, 1.5, 0.2]), 0)
(array([5.2, 3.4, 1.4, 0.2]), 0)
(array([4.7, 3.2, 1.6, 0.2]), 0)
(array([4.

In [23]:
##decorators
def dec(func):
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)
        return result
    return wrapper
@dec
def iris(data, target):
    processed_data = [sum(row) for row in data]
    result = {"processed_data": processed_data, "target": target}
    return result
result = iris(data, target)
print(result)


{'processed_data': [10.2, 9.5, 9.4, 9.399999999999999, 10.2, 11.4, 9.700000000000001, 10.1, 8.9, 9.6, 10.8, 9.999999999999998, 9.299999999999999, 8.5, 11.2, 12.000000000000002, 11.000000000000002, 10.3, 11.5, 10.7, 10.7, 10.700000000000001, 9.399999999999999, 10.599999999999998, 10.299999999999999, 9.799999999999999, 10.4, 10.399999999999999, 10.2, 9.7, 9.7, 10.700000000000001, 10.9, 11.299999999999999, 9.7, 9.599999999999998, 10.5, 10.0, 8.9, 10.2, 10.100000000000001, 8.4, 9.1, 10.7, 11.2, 9.5, 10.699999999999998, 9.399999999999999, 10.7, 9.9, 16.299999999999997, 15.600000000000001, 16.4, 13.100000000000001, 15.4, 14.3, 15.9, 11.600000000000001, 15.4, 13.200000000000001, 11.5, 14.600000000000001, 13.2, 15.1, 13.4, 15.600000000000001, 14.6, 13.6, 14.4, 13.1, 15.700000000000003, 14.2, 15.200000000000001, 14.799999999999997, 14.900000000000002, 15.4, 15.799999999999999, 16.4, 14.9, 12.8, 12.799999999999999, 12.600000000000001, 13.6, 15.399999999999999, 14.4, 15.5, 16.0, 14.3, 14.0, 13.3,